extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - [feat, fix, chore, refactor, test, docs, style, perf, ci, build, revert]
  subject-case:
    - 2
    - never
    - [sentence-case, start-case, pascal-case, upper-case]
